### ISSUE TITLE
Flycheck indicator colors are always the same

### ISSUE THREAD

**Issue by jwintz** [jwintz/prolusion#1]
Even though prolusion theme defines the faces, indicators are always of the same color.

Possible investigations:
- deactivate vector bitmaps
- deactivate theme

**Comment by jwintz** [comment]
More on that issue:
- https://github.com/flycheck/flycheck/issues/811
- https://github.com/Sarcasm/flycheck-irony/issues/13

Seems to be an emacs bug. Needs reporting.

**Comment by emanjavacas** [comment]
Hi! I am having the same, no updates so far?

**Comment by jwintz** [comment]
Hi! No, I have tried with emacs' git HEAD and I'm still having the issue.

**Comment by jwintz** [comment]
Fixed in https://github.com/flycheck/flycheck/issues/811#issuecomment-296611322.
